### ISSUE TITLE
Mimic DCG

### ISSUE THREAD

**Issue by vsraptor** [ML-KULeuven/problog#48]
Trying to mimic DCG ..
```

r1([a, b|A], A).
r2([a, c|A], A).

r3(A,D) :-
 r1(A, B),
 B=[x|C],
 r2(C,D).


r4(L,R):- r1(L,R) ; r2(L,R).

```
those work ... and then tring to add probabilities :
```

0.4::r5(L,R) :- r1(L,R).
0.6::r5(L,E) :- r2(L,R).


?- r5([a|X],[]).
Encountered a non-ground probabilistic clause at 13:6 in ./p-abac.pl.

```
As you see I'm getting the above error..

Red the answer : 5.1. I get a NonGroundProbabilisticClause error. What is going on?

but still don't get it !!
What I'm doing wrong ?

**Comment by twinters** [comment]
This error stems from the fact that your query can not be grounded.
This is because there are free variables, e.G. in `0.6::r5(L,E) :- r2(L,R).`, where `R` can be any value, causing `L` to be any list that starts with [a,c]. Did you mean to put in `R` instead of `E` in that clause?

These ProbLog examples might help you on your quest of implementing a probabilistic DCG:
- [Probabilistic Context Free Grammar in Problog](https://dtai.cs.kuleuven.be/problog/tutorial/various/06_pcfg.html)
- [Stochastic Logic Program in Problog](https://dtai.cs.kuleuven.be/problog/tutorial/various/06_slp.html)
