### ISSUE TITLE
Identifying which clauses are triggered when running the inference engine

### ISSUE THREAD

**Issue by Sidney2408** [ML-KULeuven/problog#59]
Hi there, 

let's say I have defined a clause like this:

"""
is_blocked(T,X):- contains(T, X, I), size(T, I, S1), size(T, X, S2), more_than(_, S1,S2).
"""

does Problog have any functionality that allows me to identify if this clause evaluates to true and if it evaluates to false, can the engine flag which predicates in the if clause evaluates to false?

**Comment by rmanhaeve** [comment]
Hi Sidney

The functionality you describe sound to me like it's just inference. So you'd query the probability of is_blocked(T,X) being true. I don't know if the engine can flag at which point the clause failed, but you could modify the program to provide this information perhaps.

Since this is not really an issue, I'm closing it for now. If you have further questions, feel free to mail me (my e-mail address is visible in my profile).

Kind regards,
Robin

**Comment by krishnangovindraj** [comment]
Running `problog --trace filename.pl`  will give you a trace (of every step, so it can be long).

if you look for lines starting with 'fail' (with some indentation before it), it should tell you which predicates are failing. It might be helpful to start at the last fail in a block of fails and work your way upwards.
