### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by rmanhaeve** [ML-KULeuven/problog#62]
There are several deprecation warnings that need to be resolved:

DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()

**Comment by VincentDerk** [comment]
I have a fix for the first and third warning. Where is the second warning from? I don't seem to receive that warning, perhaps I'm looking at a different branch?

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working`

**Comment by rmanhaeve** [comment]
Seems already fixed in newer version of ProbLog. It's still an issue in the pip version perhaps.
