### ISSUE TITLE
dsharp.exe Windows binary throws error

### ISSUE THREAD

**Issue by plison** [ML-KULeuven/problog#91]
Thanks for the nice work with ProbLog! When trying to run ProbLog on Windows, I get an error with the dsharp.exe binary: 
![image](https://user-images.githubusercontent.com/11574012/192526082-9ce43583-50ca-4133-9be1-ddaa93ffcde2.png)

I'm running Windows 10, with the latest version of Problog (2.2.3).

This error is a bit annoying since it seems that the PySDD library cannot apparently be compiled on Windows. And recompiling dsharp from https://github.com/QuMuLab/dsharp/ on Windows does not seem straightforward either...

Everything runs fine when running ProbLog on Linux, however.

**Comment by VincentDerk** [comment]
Hi,

1) Which conda version are you using? `conda --v`

2) Does the .exe within this .zip work?
Temporarily replace the dsharp.exe in the [bin folder](https://github.com/ML-KULeuven/problog/tree/master/problog/bin/windows) with the one in here: [dsharp_static.zip](https://github.com/ML-KULeuven/problog/files/9662489/dsharp_static.zip)

**Comment by plison** [comment]
Thanks! I'm using conda 4.12. Yes, when using the dsharp.exe executable in the ZIP file, the error disappears, and ProbLog seems to run without problems :-)

**Comment by VincentDerk** [comment]
Hmm.. I thought perhaps this was related to conda shipping a libstdc++ that did not contain `throw_bad_array_new_lengthv` [1,2], but that was [supposedly fixed in conda 4.10.3](https://github.com/conda/conda/issues/10757#issuecomment-962281162). Either way it might be easiest to just use a statically compiled dsharp instead (like the one in the zip). Unless someone has a better proposal, I will replace the executable in the next ProbLog release.
 
[1] https://github.com/conda/conda/issues/10757#issuecomment-962281162
[2] https://github.com/stan-dev/pystan/issues/294
