### ISSUE TITLE
numbervars/2 is not working

### ISSUE THREAD

**Issue by rmanhaeve** [ML-KULeuven/problog#95]
Produces a UnifyError

To reproduce:
```
query(numbervars(a(X))).
```

**Comment by VincentDerk** [comment]
I get the following error on your example:

UnknownClause: No clauses found for 'numbervars/1' at 1:7.

, which seems expected to me. 

You probably mean to use numbervars/2 or numbervars/3 ([libraries](https://problog.readthedocs.io/en/latest/prolog.html#problog-specific-builtins)).

**Comment by rmanhaeve** [comment]
Sorry, the example that breaks it is
```
query(numbervars(a(X),0)).
```

**Comment by VincentDerk** [comment]
Ah yes.

Normal usage: `query(numbervars(a(X),Y)).`
Output: `numbervars(a(X1),a($Var(0)))`

What happens is [engine_builtin.py::_built_in_numbervars()](https://github.com/ML-KULeuven/problog/blob/c720e76d3791af6333dde5565648c48ebb03df21/problog/engine_builtin.py#L1123) fails when calling unify_value. Because [engine_unify.py::unify_value()](https://github.com/ML-KULeuven/problog/blob/c720e76d3791af6333dde5565648c48ebb03df21/problog/engine_unify.py#L81) raises the UnifyError. I am not familiar with numbervars so I'm not sure what the desired behavior is. Might need a try-catch there.
